version: '3'

services:

  db:
    image: mysql:8.0.17
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sourceshoot
      MYSQL_DATABASE: sourceshoot
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  sourceshoot_backend:
    build: ../sourceshoot-backend/backend
    container_name: sourceshoot-backend
    ports:
      - "4200:4200"
    depends_on:
      - "db"
    restart: always

  sourceshoot_frontend:
    build: ../sourceshoot-frontend
    container_name: sourceshoot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - sourceshoot_backend
    restart: always

volumes:
  dbdata:
