version: '3'

services:

  db:
    image: mysql:8.0.17
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sourceshoot
      MYSQL_DATABASE: sourceshoot
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  go-backend:
    build: ../sourceshoot-backend/backend
    ports:
      - "4200:4200"
    depends_on:
      - "db"
    restart: always

  react-frontend:
    build: ../sourceshoot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - go-backend
    restart: always
  
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - "db"
      - "go-backend"
      - "react-frontend"

volumes:
  dbdata:
